[network]
type = 'RGT'
class = 'rgt.RGT'
scale = 4
img_size = 64

[network.configs]
upscale = 4
in_chans = 3
img_size = 64
img_range = 1.0
depth = [6,6,6,6,6,6,6,6]
embed_dim = 180
num_heads = [6,6,6,6,6,6,6,6]
mlp_ratio = 2
resi_connection = '1conv'
split_size = [8,32]
c_ratio = 0.5